- .travis.yml
- README.md
- deployment/deployment.yml
- deployment/ingress.yml
- deployment/service.yml
- nginx/Dockerfile
- nginx/nginx.conf
- scripts/deploy.sh
- Add kubernetes deployment
- Add travis configuration (runs unit tests, builds and deploys `devel` to k8s)
- Update README with development workflow commands
- Create nginx image to serve vue app with browser caching disabled
> Deployment

- src/App.vue
- src/components/LoginDialog.vue
- src/router.ts
- src/store/index.ts
1. This is an example of how routes can be protected based on authorization state.
2. Also replace the history of a user upon logout.
> Chore guard routes

- src/components/shared/NewProject.vue
Keeping the PRs small from now on. This is a change requested by @kvikshaug on #8 - https://github.com/DD-DeCaF/caffeine-vue/pull/8#pullrequestreview-233058310
> feat: wait for the token to be refreshed before concluding project creation

- src/App.vue
- src/main.ts
- src/router.ts
- src/startup.ts
- src/store/index.ts
- src/store/modules/session.ts
* Route guard waits for local storage reading to have happened
* Add gaurds to further routes
> refactor: initialize store from local storage before creating Vue app

- .env
- package-lock.json
- package.json
- src/components/InteractiveMap/Card.vue
- src/components/InteractiveMap/CardDialog.vue
- src/components/InteractiveMap/Escher.vue
- src/components/InteractiveMap/InteractiveMap.vue
- src/components/InteractiveMap/Legend.vue
- src/settings.ts
The following has been implemented:
Known bugs:
Remaining features for later PRs (split up to make reviews a bit more manageable):
- Adding/knocking out reactions
- Adding/knocking out genes
- Editing objective
- Editing bounds
- Default bounds are not available, so they are displayed as -1 in the map
- Reactions that are not in the model are not marked as red on the map
> More interactive map features

- src/components/Jobs/JobResultsTable.vue
- src/store/modules/models.ts
- src/views/Jobs/JobDetails.vue
- src/views/Jobs/JobResultsTable.vue
todo:
1. expandable rows with menu for heterologous reactions
2. visualization functionality
> Job detail table

- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/CardDialog.vue
- src/views/InteractiveMap/CardDialogDataDriven.vue
- src/views/InteractiveMap/CardDialogDesign.vue
- src/views/InteractiveMap/Escher.vue
- src/views/InteractiveMap/InteractiveMap.vue
> Data driven cards

- package-lock.json
- package.json
- src/main.ts
This integrates sentry with our Caffeine-Vue. 
Please bear this in mind:
```Vue Error Handling
Please note that if you enable this integration Vue internally will not call logError due to a currently know limitation see: GitHub Issue.
This means that errors occurring in the Vue renderer will not show up in the developer console.```
- https://docs.sentry.io/platforms/javascript/vue/?_ga=2.242518274.1462329972.1557918583-653711018.1550504433
> feat: integrate sentry

- src/views/InteractiveMap/CardDialogDesign.vue
Fixes https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/902
> Fix default bounds

- src/store/modules/designs.ts
- src/views/Designs.vue
- src/views/Jobs/Jobs.vue
Done:
1. Request full information from BIGG on added reactions when fetching designs
2. Add progress slot for designs and jobs data tables indicating that data is fetching
> Added reactions

- src/store/modules/designs.ts
- src/store/modules/jobs.ts
- src/store/modules/projects.ts
- src/views/Designs.vue
- src/views/Jobs/Jobs.vue
- src/views/Maps.vue
- src/views/Models.vue
- src/views/Projects.vue
Done:
1. Before store designs in Vuex, parse the added reaction property assuming that we will save full reaction information later in the design storage
2. Store the request promise in all stores and use it for loader indicating that data is fetching
3. Add loaders when deleting items for all data tables
> Data tables

- src/views/Jobs/JobResultsTable.vue
> Jobs expanded rows

- src/App.vue
- src/store/modules/projects.ts
- src/views/Design.vue
- src/views/Projects.vue
This is my suggestion of how to refactor the project theming code.
> refactor: shift functionality to projects store

- src/views/Jobs/JobResultsTable.vue
Thanks @ChristianLieven and @kvikshaug
> fix: min max attributes on sliders were not rounded

- src/components/DeletionDialog.vue
- src/store/modules/designs.ts
- src/store/modules/interactiveMap.ts
- src/views/Designs.vue
- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/CardDialog.vue
- src/views/InteractiveMap/CardDialogDesign.vue
- src/views/InteractiveMap/Escher.vue
- src/views/InteractiveMap/InteractiveMap.vue
- src/views/Jobs/JobResultsTable.vue
> Save designs

- src/store/modules/interactiveMap.ts
- src/views/Designs.vue
- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/CardDialog.vue
- src/views/InteractiveMap/InteractiveMap.vue
- src/views/Jobs/JobResultsTable.vue
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/910
> Open dialog when adding new design or data driven card

- src/components/NewModel.vue
fixes that maps weren't segemented
> fix: show segmented maps

- src/views/InteractiveMap/CardDialogDesign.vue
- src/views/InteractiveMap/MetaboliteDialog.vue
- src/views/InteractiveMap/ReactionDialog.vue
> Add arbitrary reaction

- package-lock.json
- package.json
Fixes https://nvd.nist.gov/vuln/detail/CVE-2019-10742
> chore: update axios

- package-lock.json
- package.json
- src/types/escher.d.ts
- src/views/InteractiveMap/Escher.vue
New version includes upstream changes and improved merging of added reactions
> chore: Update @dd-decaf/escher

- src/views/Jobs/JobResultsTable.vue
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/957
> Cofactor swap

- src/views/Jobs/JobResultsTable.vue
1. If id-mapper returned several bigg ids mapped to metanetx id of metabolite, take the one that is in the model
2. Remove compartment from metabolite id when adding reaction with swapped cofactors, so it will not be doubled later
> Map to bigg

- src/store/modules/jobs.ts
- src/views/Jobs/JobResultsTable.vue
- src/views/Jobs/Jobs.vue
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/928
If user chose anaerobic conditions for the job, then during the visualization we need to set lower bound of the `EX_o2_e` reaction to 0
> Aerobic anaerobic

- src/views/Design.vue
- src/views/Jobs/JobDetails.vue
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/960
> Change design form

- package-lock.json
- package.json
- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/Escher.vue
Requires https://github.com/DD-DeCaF/escher/pull/25
TODO:
> Force Escher to make added metabolites primary

- src/views/Jobs/JobResultsTable.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1003
> fix: set objective to the optimization target

- src/store/modules/interactiveMap.ts
- src/views/Designs.vue
- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/InteractiveMap.vue
- src/views/Jobs/JobResultsTable.vue
Depends on https://github.com/DD-DeCaF/simulations/pull/140
> Let the user know if the model is infeasible

- src/views/InteractiveMap/Card.vue
> Show objective and flux on DiffFVA cards too

- package-lock.json
- package.json
- src/views/InteractiveMap/Escher.vue
With https://github.com/DD-DeCaF/escher/pull/27, we no longer need to update state after changing maps.
> Escher redrawing

- src/views/InteractiveMap/Card.vue
Related to https://github.com/DD-DeCaF/caffeine-vue/pull/125
> Hide objective and flux on DiffFVA cards showing score

- src/components/ModificationsTable.vue
- src/views/InteractiveMap/CardDialogDesign.vue
- src/views/InteractiveMap/CardDialogDiffFVA.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1011
> Add a readonly modifications table to DiffFVA card dialog

- src/components/LoginDialog.vue
- src/components/RegisterDialog.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1037
> Registration

- src/App.vue
- src/components/DeletionDialog.vue
- src/components/NewExperiment.vue
- src/router.ts
- src/store/modules/experiments.ts
- src/views/Experiments.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1043
> Experiments table

- src/App.vue
- src/components/LoginDialog.vue
- src/components/RegisterDialog.vue
- src/router.ts
- src/store/index.ts
- src/views/PasswordReset.vue
- src/views/ResetRequest.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1036
> Reset password

- package-lock.json
- package.json
- src/views/InteractiveMap/Escher.vue
Fixes https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1038
> Fix visualizing added reactions

- src/components/ModificationsTable.vue
- src/store/modules/interactiveMap.ts
- src/utils/reaction.ts
- src/views/Designs.vue
- src/views/InteractiveMap/Card.vue
- src/views/InteractiveMap/CardDialog.vue
- src/views/InteractiveMap/CardDialogDataDriven.vue
- src/views/InteractiveMap/InteractiveMap.vue
- src/views/InteractiveMap/ReactionDialog.vue
- src/views/Jobs/JobResultsTable.vue
Modifications to data-driven card are now visualized and displayed in the dialog.
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/995
> Data driven visualize

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
- src/components/NewMedium.vue
- src/store/modules/media.ts
Done:
1. Submit data to warehouse
2. Use AutocompleteMnxMetabolite component to search for compounds
3. Update new medium creation to match new warehouse schema
4. Fix: selected data in autocomplete doesn't disappear when switching between tables
> Submit experimental data

- .travis.yml
- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
- src/components/NewMedium.vue
- src/store/modules/experiments.ts
- src/views/Experiments.vue
Reaction and compound search prioritizes results that exist in the relevant models (models that are related to the organism of the selected strain).
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1050
> Prioritize results

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
- src/store/modules/interactiveMap.ts
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1059
> Submit reaction and compound ids that were found in the models

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
- src/components/NewMedium.vue
- src/views/Design.vue
Comments from PR https://github.com/DD-DeCaF/caffeine-vue/pull/156 are addressed.
> Submit correct

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
Pasted reactions and compounds which have the exact match with the result from metanetx service (mnx and all ids from the annotation) are now autoselected.
TODO:
Highlight autocompletes without matches
> Autoselect exact match

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
Done:
1. Fix `required` rule for custom components
2. Mark autocompletes that have no matches between pasted data and results from metanetx service
Todo:
1. Ask user which condition or sample pasting data belongs to
> Empty autocompletes

- package-lock.json
- package.json
- src/components/ConfirmDialog.vue
- src/components/NewExperiment.vue
- src/main.ts
- src/utils/promisedDialog.ts
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1068
> feat: replace vuetify-confirm with custom component

- src/components/NewExperiment.vue
- src/components/SelectDialog.vue
Done:
1.  https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1069
2. https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1076
3. https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1054
> Select sample/condition pasted data belongs to

- src/components/NewModel.vue
- src/store/modules/models.ts
- src/views/Models.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1090
Related backend change: https://github.com/DD-DeCaF/model-storage/pull/20
> ecModel field

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
Correct identifiers are now expected from the MetaNetX backend service.
> refactor: remove namespace map

- src/components/NewExperiment.vue
- src/components/NewMedium.vue
- src/components/VNumberField.vue
- src/main.ts
- src/views/Design.vue
- src/views/InteractiveMap/CardDialogDesign.vue
- src/views/InteractiveMap/ReactionDialog.vue
- src/views/InteractiveMap/ReactionDialogMetabolite.vue
Fixes https://github.com/DD-DeCaF/scrum/issues/1070
until https://github.com/vuetifyjs/vuetify/issues/9368 is fixed
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1070
> Add v-number-field

- src/views/InteractiveMap/Escher.vue
- src/views/InteractiveMap/Legend.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1128
> map ecModel fluxes

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/VFormExtended.ts
- src/mixins/autoselectOnlyOption.ts
- src/views/InteractiveMap/CardDialogDesign.vue
Marked code could potentially break even on minor vuetify updates (though it is unlikely)
> docs: mark where we are using vuetify internals

- src/components/NewExperiment.vue
Fixes https://github.com/DD-DeCaF/scrum/issues/1144
> Fix pasting reaction found in model

- src/components/NewExperiment.vue
Fixes https://github.com/DD-DeCaF/scrum/issues/1143
> Fix pasting into date time fields

- src/components/NewExperiment.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1138
> feat: display organism name in strains autocomplete

- src/components/NewExperiment.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1142
> Order upload

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1145
> feat: add tooltip to reaction and compound autocomplete items

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
Now the connection error message will take preference, rather than just
displaying "Required" in both cases.
> refactor: switch rules order

- src/components/NewExperiment.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1131
> feat: add validation for datetime fields

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
v1: https://github.com/DD-DeCaF/caffeine-vue/pull/160 fixed infinite requests when input was not focused (paste two rows)
v2: https://github.com/DD-DeCaF/caffeine-vue/pull/173 fixed infinite requests when input lost focus (click outside before loaded)
v3: fixes infinite requests when input is null (click outside after loaded)
@kvikshaug First two commits are for you :D
> Fix infinite requests in mnx autocomplete (v3)

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
- src/components/NewExperiment.vue
- src/components/UniprotInput.vue
Done:
- Add input clear functionality to reaction, compound and protein fields
- Replace dialog with tooltip for protein field
> Small features

- src/components/AutocompleteMnxMetabolite.vue
- src/components/AutocompleteMnxReaction.vue
Applies a fix similar to UniProt in https://github.com/DD-DeCaF/caffeine-vue/pull/183/commits/88441793f9e3f085821989acc4e7b911627b7319
> fix: pasting same value as in the input for MNX

- src/components/NewExperiment.vue
- src/components/UniprotInput.vue
- src/main.ts
Part of https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1152.
Done: refactor components to support batch retrieval of protein data from UniProt service.
For now `v-model` for `UniprotInput` isn't implemented, so pasted data only saved in the `NewExperiment` component's data, but isn't displayed.
Updated: pasted proteins are now displayed
> Bulk requests for proteomics data

- src/components/NewExperiment.vue
- src/components/UniprotInput.vue
- src/views/InteractiveMap/CardDialogDataDriven.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1167
Depends on: https://github.com/DD-DeCaF/warehouse/pull/21
> Uniprot identifiers

- src/components/NewExperiment.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1153
We are defining `rules` property on each table.
Based on that we are checking if all items in particular table are valid.
> Validate all pages

- src/components/NewExperiment.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1207
> feat: validate only a single growth rate per sample

- src/views/InteractiveMap/Card.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1206
From a clean branch this time, should hopefully now be able to merge into devel.
> fix: enzyme usage slider only shown for ec models

- src/App.vue
- src/router.ts
- src/utils/utility.ts
- src/views/CommunityModeling.vue
closes https://github.com/DD-DeCaF/scrum/issues/1239
Adds a new component for community modeling on the platform.
> Com modeling

- src/views/CommunityModeling.vue
> feat: add search on crossfeed table 

- src/store/index.ts
- src/store/modules/media.ts
- src/views/CommunityModeling.vue
- src/views/Media.vue
@ChristianLieven I created a separate branch so that you can review only my changes - could you look over this? When done I'll merge both branches.
I have not looked into the identifier issues yet, so created media will not work well with our models in the current state. I think we need to do some refinement/brainstorming on that issue. Issue on that [here](https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1280), please prioritize as you see fit - but I'd recommend we discuss it this sprint if community modeling with custom medium is going to be part of the review.
> Media crud - final touches

- src/views/CommunityModeling.vue
added watcher to update viz on searches on the table, wasn't able to fit in the last pr in time. @ChristianLieven, if you have time can you take a look?
> feat: add search watcher for viz

- src/views/CommunityModeling.vue
> feat: add table download
