DD-DeCaF/caffeine-vue

.travis.yml
Here's a suggestion to never allow any issues categorized as warnings from the linter - WDYT?
=> Fail build for lint warnings

src/bigg.ts, src/components/InteractiveMap/Card.vue, src/components/InteractiveMap/CardDialog.vue, src/components/InteractiveMap/Escher.vue, src/components/InteractiveMap/InteractiveMap.vue, src/components/InteractiveMap/MethodHelpDialog.vue, src/store/modules/maps.ts, src/store/modules/models.ts, src/store/modules/organisms.ts
- Reactions on map that are not in the model highlighted in red
- Default bounds (from the model) are shown on reaction hover
- Set objective (searches through model reactions)
- Toggle objective direction
- Add reaction from BiGG universal model (note: all reactions are assumed to be reversible)
- Knock out reactions (searches through model reactions)
- Knock out genes (searches through model genes)
- Edit bounds (searches through model reactions, prefills fields with default bounds)
Remaining:
=> Interactive map

src/views/Designs.vue, src/views/InteractiveMap/CardDialog.vue, src/views/Jobs/Jobs.vue, src/views/Maps.vue, src/views/Models.vue, src/views/Projects.vue
Using object destructuring in the v-slot field, combined with renaming
Vuetifys `item` to the appropriate object name, makes the related
templates a little more readable.
Note: I wasn't able to make `expanded` work with destructuring in the
items slot for the designs table.
=> Destructure slot props

src/App.vue
Since we're using a material design framework, it's good practice to use the [built-in grid system](https://vuetifyjs.com/en/framework/grid), and avoid manual css tweaks as much as possible.
This PR replaces the following line from #31 https://github.com/DD-DeCaF/caffeine-vue/blob/e53fde5bd57053e10dc3143a89dd5024afdddcaa/src/App.vue#L27 with `<v-layout column justify-space-between fill-height>`.
=> Utilize vuetify grid for nav drawer layout

src/store/modules/designs.ts
The design storage has been refactored to allow any object structure in the design fields now, so we can decide on the schema on the frontend - and we don't need to serialize the data to json anymore.
=> Expect objects in design fields

src/store/modules/designs.ts, src/store/modules/interactiveMap.ts, src/store/modules/models.ts, src/views/Designs.vue, src/views/InteractiveMap/Card.vue, src/views/InteractiveMap/CardDialog.vue, src/views/InteractiveMap/CardDialogDesign.vue, src/views/InteractiveMap/Escher.vue, src/views/InteractiveMap/InteractiveMap.vue
In order to facilitate this, a couple extra features were necessary:
- Models are now not stored on the cards, but purely in the store
- Lazy loader action `withFullModel` in the model store lets callers guarantee that full model is available
- When adding reactions, model is now not directly modified, but a computed property based on the original model and card modifications
- Some escher sync issues are resolved
With this in place, the Designs component is now able to commit a card and redirect to the interactive map, visualizing the selected design(s).
=> Visualize designs

src/store/modules/interactiveMap.ts, src/store/modules/models.ts, src/views/Designs.vue, src/views/InteractiveMap/Escher.vue, src/views/InteractiveMap/InteractiveMap.vue, src/views/Jobs/JobResultsTable.vue
- The selected map is now saved in the store so that when you leave & go back to the interacitve map you get the same map
- Visualizing jobs now shows a little loader to show user that something is happening
- Fixed reactivity issues so that added reactions are always drawn on the map when visualizing jobs
=> Draw added reactions

src/components/NewMap.vue, src/components/NewModel.vue, src/components/NewOrganism.vue, src/views/Maps.vue, src/views/Models.vue
In auto-complete components we used to append the buttons for creating
new elements. With long lists the button would not be immediately
visible to users.
Some further observations:
1. Currently, we register all components globally at the moment (using `Vue.extend`). We might want to change this in future for optimization. See [the documentation on this topic](https://vuejs.org/v2/guide/components-registration.html) for more information.
2. I ran into a problem with exceeding the stack size when registering components within components. We might have to re-factor so that the components are included only once in the DOM and then opened by global store or via events.
3. This is more of a question: @phantomas1234 what about the model edit dialog on the interactive map? Should users be able …
=> refactor: prepend all "New" buttons

.travis.yml
This makes sure that [lint rules that only apply for production](https://github.com/DD-DeCaF/caffeine-vue/blob/devel/.eslintrc.js#L8) causes PR builds to fail.
=> Lint with production mode

src/views/Jobs/JobResultsTable.vue
Done:
- in the expanded row manipulations should be sorted by score
- add tooltip on manipulation showing the score
- add warning snackbar when visualizing diff_fva method
- when visualizing job with knockouts, check if we have a response from bigg for the details, otherwise we need to display only id on the dialog
=> Job result table

src/App.vue, src/store/index.ts, src/store/modules/designs.ts, src/store/modules/experiments.ts, src/store/modules/jobs.ts, src/store/modules/maps.ts, src/store/modules/models.ts, src/store/modules/organisms.ts, src/store/modules/projects.ts, src/views/Design.vue, src/views/Jobs/JobDetails.vue, src/views/Jobs/JobResultsTable.vue, tests/unit/app.spec.ts
It's inconvenient that the current fetchError mutation silently hides the underlying issue. The original idea was that setting the error object in the store makes it easy to inspect the problem, but the object is not really inspectable in the Vue devtools. So you need to add debugging statements locally and reproduce the issue to get any insight into the original error.
With this change, the issue will at least be reported to Sentry in prod/staging environments.
=> Report fetchError to Sentry

src/components/NewModel.vue
This was broken since 59c22779e499eb4b6b221cb3cd9b86fdd0425bab
=> fix: allow preferred map to be empty

src/components/LoginDialog.vue, src/components/NewMap.vue, src/components/NewModel.vue, src/components/NewOrganism.vue, src/components/NewProject.vue, src/store/modules/maps.ts, src/store/modules/models.ts, src/store/modules/organisms.ts, src/store/modules/projects.ts, src/utils/utility.ts, src/views/InteractiveMap/InteractiveMap.vue, src/views/Maps.vue, src/views/Models.vue, src/views/Projects.vue
Fixes:
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/920 
and 
https://app.zenhub.com/workspaces/caffeine-platform-59dd1cab2fbdf4155c45e6e9/issues/dd-decaf/scrum/919
For the latter I abstracted Ali's computed property for maps() from the InteractiveMap component. So in theory one could use that now to get segmented lists of any combinations of organisms, projects, models, maps. This can be reduced or extended depending on our requirements.
=> Fix submit on enter

src/views/InteractiveMap/Escher.vue
Enables the Escher build functions and hides the menu bar that allows users to heavily edit Escher parameters (changing models and maps, colours, settings, etc) outside of Caffeine's influence.
=> Escher builder

.env.demo, scripts/demo.sh
A demo mode is needed to facilitate the deployment of Caffeine for evaluation purposes (see also https://github.com/dd-decaf/caffeine-bootstrap) into an environment without internet access.
Also, a script for generating a demo image of caffeine-vue and pushing it to Dockerhub has been included.
=> feat: add demo mode

.eslintrc.js, src/views/InteractiveMap/CardDialogDesign.vue, src/views/InteractiveMap/ReactionDialogMetabolite.vue
This is a suggestion to add the [`curly`](https://eslint.org/docs/rules/curly) eslint rule to require curly braces for code clarity. For example, the following:
```
if (foo) foo++;
```
Must be rewritten as:
```
if (foo) {
foo++;
}
```
=> Require curly braces

src/store/modules/interactiveMap.ts, src/views/InteractiveMap/CardDialogDesign.vue
While deleting added reaction modification, we are checking if that reaction was knocked out before to delete also that knockout. Previously the last reaction knockout was removed regardless of id.
=> fix: undo reaction knockout

src/components/NewModel.vue, src/components/NewOrganism.vue, src/views/InteractiveMap/CardDialogDataDriven.vue, src/views/Models.vue
Example
- [Before](https://user-images.githubusercontent.com/3758846/60796620-07274780-a16e-11e9-8a41-bb9e994ed226.gif)
- [After](https://user-images.githubusercontent.com/3758846/60797727-23c47f00-a170-11e9-83b5-71c2025b8d2a.gif)
- data driven card returns conditions with same names (A1) for different experiments
- when using `return-object` without `item-value`, items will be compared by displayed text https://github.com/vuetifyjs/vuetify/issues/7775
=> fix: added missing item-value to dropdowns with return-object

src/views/Jobs/JobResultsTable.vue
Without stoichiometry, it defaults to NaN and puts all metabolites on
one side (all products, because NaN < 0 is false)
| Before | After |
| --- | --- |
| ![b](https://user-images.githubusercontent.com/3758846/60967301-a0935c80-a31a-11e9-82c2-aa4508b9ed38.png) | ![a](https://user-images.githubusercontent.com/3758846/60967299-9f622f80-a31a-11e9-9537-33b594dcbbcc.png) |
=> fix: visualize cofactor swap results by passing stoichiometry to Escher

src/views/InteractiveMap/Escher.vue
fixes the problem that the diffFVA scores would no longer show on the interactive map.
=> fix: escher builder.options had been deprecated

src/store/modules/interactiveMap.ts, src/views/InteractiveMap/InteractiveMap.vue, src/views/Jobs/JobResultsTable.vue
- Moves the DiffFVA logic from the simulation step back to being resolved when creating the card, and sets the modifications on the actual card.
- Now there's no need for the `simulateDiffFVA` function in the interactive map component, so reuse the simulation logic for a design card. (We should do the same for data driven cards actually.)
- Fix: When finding the original bounds for the manipulations, search also in the card's added reactions (so that the heterologous reactions can be found).
=> Apply DiffFVA modifications correctly

src/store/modules/interactiveMap.ts, src/views/InteractiveMap/CardDialogDiffFVA.vue, src/views/InteractiveMap/Escher.vue, src/views/InteractiveMap/InteractiveMap.vue, src/views/Jobs/JobResultsTable.vue
Removes obsolete logic associated with previous diffFVA response from the backend. 
The new response now looks like this:
```
{
id: string;
score: number;
value: number;
direction: ["up", "down", "invert"];
}
```
The new logic now simply constrains the model with the 'value' parameters from diffFVA and runs a simulation once:
```
direction === "up"
& value > 0
--> reaction.lower_bound = value
& value < 0
--> reaction.upper_bound = value
```
```
direction === "down"
& value > 0
--> reaction.upper_bound = value
& value < 0
--> reaction.lower_bound = value
```
```
direction === "invert"
& value > 0
--> reaction.lower_bound = value
& value < 0
--> reaction.upper_bound = value
``` 
The 'score' parameter is now displayed when toggled on the card.
=> Frontend fva

src/views/InteractiveMap/Card.vue
Instead of returning null, it was silently throwing an error
This condition is now consistent with https://github.com/DD-DeCaF/caffeine-vue/blob/77e2db6ab02427e6c7dbb30b0db18e905ba46fa2/src/views/InteractiveMap/Card.vue#L73
=> fix: error when getting production

src/views/Jobs/JobResultsTable.vue
Job results should be filtered out only if both growth and production are 0 or null
=> fix: keep results where growth or biomass is positive

src/views/Jobs/JobResultsTable.vue
Up to https://github.com/DD-DeCaF/caffeine-vue/pull/120 a silent error wasn't easily noticeable, but now it completely broke the second card (when adding two diff-fva rows from job results to visualizations)
=> Fix flux when visualizing two rows from job results

src/store/modules/interactiveMap.ts, src/views/InteractiveMap/Card.vue
Though this might make more sense since the dialog is readonly.
=> Use info icon for DiffFVA card dialog

src/views/InteractiveMap/Escher.vue
Measurements have a `type` field which can be "reaction" or "compound".
For a reaction, we should highlight the reaction id as measured. However for the compound, it's not so clear - we could find the exchange reaction and mark it as measured (since that's what we constrain) but many maps don't have the exchange reactions drawn.
In any case, the current logic was trying to find the compound identifier as a reaction and that's of course wrong.
=> fix: highlight only reaction measurements with glow

src/components/CompoundLink.vue, src/components/ReactionLink.vue, src/store/modules/interactiveMap.ts, src/views/Designs.vue, src/views/InteractiveMap/Card.vue, src/views/InteractiveMap/CardDialogDataDriven.vue, src/views/InteractiveMap/Escher.vue, src/views/InteractiveMap/InteractiveMap.vue, src/views/Jobs/JobResultsTable.vue
- Handles experimental data correctly and forwards to simulation service (depends on https://github.com/DD-DeCaF/simulations/pull/145)
- New components to display compound/reaction identifier and link to remote database if recognized (more database URLs can easily be added)
- Tables to list experimental data are modified a bit, now a separate table for each measurement type
=> Update data-driven cards for new warehouse schema

src/views/InteractiveMap/Card.vue
Fixes https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1031
The destroyed handler works when navigating away (and keeping the cards
in the store), but fails when the card has been removed.
Instead, just deactivate the dialog toggle right after it has been used.
This way we don't need to worry about the component's lifecycle.
=> fix: avoid using destroyed handler

src/components/NewExperiment.vue, src/components/UniprotInput.vue, src/views/InteractiveMap/CardDialogDataDriven.vue
- Add proteomics table in new experiment dialog
- Uses new Uniprot component which matches against https://www.uniprot.org/uniprot/ (service doesn't provide search, so needs to be exact match)
- Show proteomics in data driven card dialog
- Unrelated fix: Better display if strain has no genotype modifications
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1082
Related backend change: https://github.com/DD-DeCaF/warehouse/pull/20
=> Proteomics

src/components/NewExperiment.vue
When using pagination, data table's indeces on every page start from 0. We rely on index when pasting data and creating new strain or medium. To get the correct index, current page and amount of rows per page now are considered
=> Fix indeces when using pagination

src/components/NewExperiment.vue
This fixes "Change main field strategy" from https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1153
- Removed mainField
- Nothing is required on initialization
- If a row is added or a value inserted, fields in that table become required
(*except optional fields*)
=> Fields become required if first row is not empty, or if any row has been added

src/components/NewExperiment.vue
For https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1153
todo:
- performance issues above 1000 items: each keystroke takes about ~200ms
- use the same function for all tables
- move all rules to `tables[*].rules`
=> WIP: validate all pages of proteomics

package-lock.json, package.json
The latest minor version breaks html compatibility for hints.
=> chore: pin vuetify v1.5.14

src/components/NewExperiment.vue
The batch endpoint returns all the protein names but we only care about the recommended one. Before:
After:
=> feat: only select recommended protein name

src/components/NewExperiment.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1154
Proposed solution: to add button that sorts array to display invalid rows first.
Issues with initial idea to add a checkbox to filter the array:
1. If checkbox is selected, the moment user changes the row to be valid, that row will disappear, that might be confusing. Keeping that row displayed is also not a perfect UX solution considering that checkbox "Show only invalid rows" is selected
2. Possibility to paste data will be disabled
Update:
Pagination was changed, now user can navigate to first or last page.
=> Show invalid rows first

src/components/NewExperiment.vue
growth rate has units of `1/h`, not `mmol/gDWh`. Everywhere else in the repo the units are correct.
=> fix: units of growth rate hint

src/views/InteractiveMap/Card.vue, src/views/InteractiveMap/CardDialog.vue, src/views/InteractiveMap/CardDialogDataDriven.vue
It looks like a big changeset, but most of the changes are in the second commit which simply moves the `CardDialogDataDriven` out of the parent component, `CardDialog`. Now it's reimplementing logic from the parent, which makes it easier to control when simulations happens etc.
[The issue](https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/912) is implemented in [the third commit](https://github.com/DD-DeCaF/caffeine-vue/pull/195/commits/cbc13dd4bd24e0f96f0c10e15d4789cc0e625e74) by removing the organism drop-down and now auto-selecting the organism based on the selected strain.
The last commit implements the status [I posted about here](https://biosustain.slack.com/archives/G8SBED3C3/p1574331459000700).
=> Data driven dialog

src/components/NewExperiment.vue
Now we are using batch post endpoints for fluxomics, metabolomics and proteomics. With that it makes no sense to use progress bar any more (we were counting items that have been posted).
=> Batch endpoints

src/views/InteractiveMap/Escher.vue
some models (for instance ecModels) don't have gene names, so it's safer/simpler to match to their gene ids.
**Note:** The visualization still fails for data in scientific notation (due to low values), but that is an Escher bug that will be addressed separately.
=> fix: gene matching when showing proteomics

src/components/UniprotInput.vue
Note, I was able to confirm that this is not necessary for the batch requests.
=> Ensure exact id match on uniprot response results

src/components/NewExperiment.vue, src/views/Experiments.vue
https://app.zenhub.com/workspaces/bioviz-scrum-5d22fe4139b1324e0011234c/issues/dd-decaf/scrum/1137
With the backend quirks now fixed, the editing feature should be ready and function as expected.
On submit, we upload all data in the dialog, then on success we delete the previous related data. Due to this implementation, the success message states that an experiment was created instead of updated, but I'm thinking it doesn't make much of a difference.
=> Edit experiments

src/views/InteractiveMap/Card.vue
Closes https://github.com/DD-DeCaF/scrum/issues/1086
The value chosen from which it starts showing up is an arbitrary low value, maybe it should be more clearly defined? 
Here's how it looks in action: 
Can whoever reads this also give me some feedback if I worked on this correctly, the way that the team would normally do this?
=> Added an Icon with a tooltip as growth rate alert to the Card component

src/store/modules/designs.ts, src/store/modules/experiments.ts, src/store/modules/interactiveMap.ts, src/store/modules/jobs.ts, src/store/modules/maps.ts, src/store/modules/media.ts, src/store/modules/models.ts, src/store/modules/organisms.ts, src/store/modules/projects.ts, src/store/modules/session.ts, src/store/modules/strains.ts, src/types/vuex.d.ts
The interface is necessary for using rootState inside store modules.
Otherwise the compiler complains.
=> refactor: define RootState TypeScript interface

src/views/Jobs/JobResultsTable.vue
This is the workaround I mentioned last week to filter out modifications where the value from metabolic ninja is 0.
=> fix: heterogenous array returned when prediction has value 0
